### PR TITLE
Feature/litttle api improvement in MtimeDB

### PR DESCRIPTION
**Pull request by palao**
I am suggesting some changes to `MtimeDB` in this PR:

- (some) unit tests are added (there were none),
- a new `make_readonly` method is added to replace hard-to-read code like:
```
mtimedb.filename = None
```
with a more explicit and clear code:
```
mtimedb.make_readonly()
```
- also the boolean `is_readonly` property is added to question instances:
```
if mtimedb.is_readonly:
    ...
```
- some refactors

it is my first pull request and I'm not sure whether it is OK or not. I would keep refactoring a little bit more the `MtimeDB` class but I thought it would be good to make the PR before going further.

### CODE REVIEW

**Review by zmedico — APPROVED** [review]
LGTM (aside from black formatting and pylint issue). Thanks!

**Comment by palao** [comment]
Sorry! I completely forgot about pylint and black.
Next time I'll do it better. But thanks for accepting it!

**Comment by zmedico** [comment]
> Should I commit after passing thru black and pylint?

Yes, please do.

**Comment by palao** [comment]
I'm sorry but I don't understand why that happens... Any idea?

**Comment by floppym** [comment]
CI seems to be broken at the moment, probably something to do with a new version of pylint.

**Comment by floppym** [comment]
See https://github.com/gentoo/portage/pull/837 for the CI "fix".

**Comment by thesamesam** [comment]
Thanks floppym. Could you rebase @palao?

**Comment by floppym** [comment]
Also, it would be nice to avoid the merge commit. If possible, please rebase the entire patchset on current master, without merging.

**Comment by floppym** [comment]
One last thing: please review our [copyright policy](https://www.gentoo.org/glep/glep-0076.html), and add `Signed-off-by` to your commit messages.

**Comment by floppym** [comment]
Pushed as e22cf80ec99c52c1192ecf99f6b66d1d892f3f86.

**Comment by thesamesam** [comment]
Thank you!

**Pull request closed without merging**
