### PR TITLE
bin/phase-helpers.sh: Added code from eapply_user to handle multiple calls

### PR DESCRIPTION
**Pull request by wltjr**
Added _DEFAULT_SRC_PREPARE_CALLED and _DEFAULT_EAPPLY_CALLED to allow tests to see if either have been called, like eclasses calling default in custom src_prepare

### CODE REVIEW

**Comment by zmedico** [comment]
Variables like these can not be relied upon in official gentoo ebuilds unless they are added as an EAPI extension.

**Comment by wltjr** [comment]
Is that way eapply_user sets a file vs var? I can switch to file in place of the variable. Or are you saying in general any such change is EAPI?

**Comment by wltjr** [comment]
This is for an eclass not ebuild, java-utils-2.eclass.

**Comment by wltjr** [comment]
Seems like this cannot take place as it needs to happen for other package managers as well.

**Comment by zmedico** [comment]
Right, for official gentoo eclasses, it has to be added as an EAPI extension.

**Comment by wltjr** [comment]
That is unfortunate as EAPI=6 will create a massive mess on the Java side, till EAPI=7 it seems. May be best to avoid for now.

**Comment by zmedico** [comment]
Just add a wrapper function in one of the java eclasses, like java-utils-eapply or something.

**Comment by wltjr** [comment]
Nothing I can do will tell me if another eclass called eapply is the problem.

**Comment by wltjr** [comment]
Unless your saying create some global wrapper that effects any eclass/ebuild call to eapply after java-utils-2 inherit.

**Pull request closed without merging**
