### PR TITLE
EbuildIpc.communicate: lockfile PermissionDenied retry

### PR DESCRIPTION
**Pull request by zmedico**
The lockfile function is expected to raise PermissionDenied if
the (root) parent process holds the lock, so retry in this case.

Bug: https://bugs.gentoo.org/468990
Signed-off-by: Zac Medico <zmedico@gentoo.org>

### CODE REVIEW

**Comment by vapier** [comment]
didn't know if you wanted to do it at this high level, or should the retry loop be inside the existing `lib/portage/locks.py:_lockfile_iteration` which has checks for different errno failure modes

**Comment by zmedico** [comment]
> didn't know if you wanted to do it at this high level, or should the retry loop be inside the existing `lib/portage/locks.py:_lockfile_iteration` which has checks for different errno failure modes

I think it's probably good enough to retry inside EbuildIpc.communicate for now, and we can evaluate adding support to _lockfile_iteration later if we find that this is useful in other cases. I'm not yet aware of any other cases where we would need this kind of retry.

**Review by vapier — APPROVED** [review]

**Comment by zmedico** [comment]
We could solve a permission race on the lockfile creation side, by doing a `chmod g+s` on the parent directory, and `umask 0002` during creation of the lockfile.

**Comment by zmedico** [comment]
Closing in favor of https://github.com/gentoo/portage/pull/768.

**Pull request closed without merging**
