### PR TITLE
ebuild.sh: add missing IDEPEND re-sourcing

### PR DESCRIPTION
**Pull request by thesamesam**

### CODE REVIEW

**Comment by thesamesam** [comment]
I'm not sure what this is about but I figured I'd throw this up either as a reminder to look into it or for somebody else to confirm it looks odd to not be there.

**Comment by zmedico** [comment]
It looks like we're also missing a B_IDEPEND setting where B_DEPEND etc are set.

**Review by zmedico — APPROVED** [review]
LGTM

**Comment by thesamesam** [comment]
thanks!

**Pull request closed without merging**
