### PR TITLE
multilib_category.py: recognize LoongArch ABIs

### PR DESCRIPTION
**Pull request by xen0n**
Add its ELF machine number constant as well. The Gentoo ARCH is "loong"; all six ABIs defined in [the LoongArch ELF psABI spec][1] are supported. The upstream binutils port currently implements [an earlier version of the spec][2]; the ILP32 ABIs are never fully implemented so far, and the value for LP64D is coincidentally the same, so the code here stays compatible.

This is preparatory work towards a port to the LoongArch architecture, which is the new RISC architecture from Loongson Corporation after switching away from MIPS.

[1]: https://github.com/loongson/LoongArch-Documentation/blob/23d53fe146a4/docs/LoongArch-ELF-ABI-EN.adoc
[2]: https://sourceware.org/git/?p=binutils-gdb.git;a=blob;f=include/elf/loongarch.h;h=b4d801ae9bd5a6c4562ca6b1cbae6e6d45d6c704;hb=HEAD

### CODE REVIEW

**Comment by mgorny** [comment]
Is there upstream binutils support for this?

**Comment by xen0n** [comment]
> Is there upstream binutils support for this?

Currently there isn't, but preliminary ports of various low-level software has already been open-sourced by Loongson:

* [binutils](https://github.com/loongson/binutils-gdb),
* [gcc](https://github.com/loongson/gcc),
* [glibc](https://github.com/loongson/glibc),
* [linux](https://git.kernel.org/pub/scm/linux/kernel/git/chenhuacai/linux-loongson.git/log/?h=loongarch-next),
* [qemu](https://github.com/loongson/qemu/pull/1).

Notably LLVM is still missing; a port of Go exists but is not upstreamable, I'm working on another port from scratch. The project seems to be quite badly rushed, and the currently published code is substantially based on respective MIPS support, with bits of RISC-V and AArch64 code taken.

However, despite the not-so-experienced teams pushing things in suboptimal manner, experiments are already underway; there's [a CLFS tutorial](https://github.com/loongarch64/website/pull/11) written, and I've already made `crossdev` toolchain and trying to get a first rootfs cross-compiled. Hardware is already out, there are boards for ~4000 CNY shipping in China.

So my question is whether accepting preliminary bits for this arch is okay for the Gentoo upstream, or should we wait before things are properly upstreamed and continue our porting work out-of-tree? I'm not planning to send any LoongArch-related ebuild modifications at present, but some small tweaks to Portage and eclasses (`toolchain-funcs.eclass` at least) are definitely needed.

**Comment by mgorny** [comment]
Well, I am somewhat concerned that the constants may change before it's final but I guess it doesn't matter much before it's widely deployed. However, could you announce your intent on gentoo-dev first? So at least we have some feedback before reserving the `ARCH` value.

**Comment by xen0n** [comment]
> Well, I am somewhat concerned that the constants may change before it's final but I guess it doesn't matter much before it's widely deployed. However, could you announce your intent on gentoo-dev first? So at least we have some feedback before reserving the `ARCH` value.

Yeah, sure! Will post on gentoo-dev later.

**Comment by xen0n** [comment]
I just did that gentoo-dev post; that was a lot of typing :joy: Now let's wait for replies...

**Comment by xen0n** [comment]
Hi, recently the binutils port got merged upstream, and their ELF psABI spec got a revision as well; code here is updated accordingly. Do we still need to wait for gcc/glibc/linux to be fully merged?

**Comment by xen0n** [comment]
Friendly ping ;)

**Comment by thesamesam** [comment]
Given that it's been merged to Binutils, I don't mind going ahead here.

**Comment by thesamesam** [comment]
Thanks a lot for your work on this! I've also merged the toolchain-funcs.eclass patch from the ML.

**Pull request closed without merging**
