### PR TITLE
Enhancement : Enable eclean-pkg to gracefully handle incomplete merge…

### PR DESCRIPTION
**Pull request by siddhanthrathod**

### CODE REVIEW

**Comment by ajakk** [comment]
Hm, is there a particular bug this is addressing? Can you tell us what problem this is supposed to solve?

**Comment by siddhanthrathod** [comment]
Its an extension for [eclean-pkgs clean invalids feature](https://github.com/gentoo/gentoolkit/commit/a16d0d4fbfb4614832c4b682b41284a9050af29f) and this will enable eclean-pkg to deal with incomplete merges from the new binhost.

**Comment by thesamesam** [comment]
Please explain what it solves in detail in the commit message:
1. What it does and why
2. How

**Comment by siddhanthrathod** [comment]
> Please explain what it solves in detail in the commit message:
> 
> 1. What it does and why
> 
> 2. How
> 
> 
> 
> Always do that :)
> 
> 
> 
> Please also include a Bug: tag for the older bug.

Okay I'll keep that in mind moving forward @thesamesam @ajakk . I'll update it in the morning.

**Comment by siddhanthrathod** [comment]
@ajakk @thesamesam is this better ?

**Comment by thesamesam** [comment]
Thank you!

**Pull request closed without merging**
