### PR TITLE
Allow building of pure Python wheel by setting "pure" appropriately

### PR DESCRIPTION
**Pull request by chewi**
It will only build a pure wheel when pure is true in all cases.

To get a pure wheel, run:
```
python -m build --wheel -Csetup-args="-Dnative-extensions=false"
```

### CODE REVIEW

**Comment by thesamesam** [comment]
Thanks! Could you update the `DEVELOPING` file too?

**Comment by chewi** [comment]
> Thanks! Could you update the `DEVELOPING` file too?

What do you want it to say exactly? Only building a pure wheel is easy, otherwise you need to consider the arch and Python versions.

**Comment by thesamesam** [comment]
> > Thanks! Could you update the `DEVELOPING` file too?
> 
> What do you want it to say exactly? Only building a pure wheel is easy, otherwise you need to consider the arch and Python versions.

I figured it was worth changing the instructions to mention:
>python -m build --wheel -Csetup-args="-Dnative-extensions=false"
and then mention that if wanting to build non-pure wheels, `python -m build --wheel`.

I can chuck that in though.

**Comment by chewi** [comment]
Okay, I added something.

**Comment by thesamesam** [comment]
Thank you!

**Pull request closed without merging**
