### PR TITLE
GitSync.update: default to "--depth 1" to avoid fetching whole Git history

### PR DESCRIPTION
**Pull request by duxsco**
This commit is explained in the corresponding bug report: https://bugs.gentoo.org/824782#c17

### CODE REVIEW

**Comment by thesamesam** [comment]
Thanks!

**Comment by duxsco** [comment]
IMHO, we should execute a `git reset --hard origin/stable` right after `git fetch origin --depth 1`. See: https://stackoverflow.com/a/41081908

**Comment by duxsco** [comment]
With the change provided by this PR, `git fetch origin --depth 1` is done if `sync-depth` is not set in repos.conf. With unset `sync-depth`, `git.py` never goes into this if condition which poses a serious issue:
https://github.com/gentoo/portage/blob/94dad3d64599f7e2c0c28e90ec4bee883746e385/lib/portage/sync/modules/git/git.py#L222-L226

**Comment by duxsco** [comment]
IMHO, a `git reset --hard origin/stable` must be done, because `git reset --merge` is insufficient. See: https://stackoverflow.com/a/41081908

**Comment by duxsco** [comment]
I created a test repo with a README.md:

1. `git clone --depth 1 https://github.com/duxsco/test.git .` results in:

screenshot_2022-04-01-025259-fs8

2. `git fetch origin --depth 1` results in:

screenshot_2022-04-01-025349-fs8

3. `git reset --merge` doesn't update `main`:

screenshot_2022-04-01-025408-fs8

4. `git reset --hard origin/main` updates `main` to the state of `origin/main`:

screenshot_2022-04-01-025427-fs8

**Comment by duxsco** [comment]
I decided to change `git reset --merge` to `git reset --hard` due to obvious reasons (see screenshots in my previous comment).

If `sync-depth` is not set to `0`, a git fetch defaults to `--depth 1` if `sync-depth` is unset and `--depth <sync-depth>` otherwise. Thus, I proposed [a change in the docs](https://wiki.gentoo.org/wiki/Talk:/etc/portage/repos.conf#clone-depth_and_sync-depth_description).

**Comment by thesamesam** [comment]
Please include all this rationale in the individual commits.

**Comment by thesamesam** [comment]
(And squash as appropriate)

**Comment by mgorny** [comment]
> I decided to change `git reset --merge` to `git reset --hard` due to obvious reasons (see screenshots in my previous comment).

I'm pretty sure we didn't want to `git reset --hard` because AFAIR it caused all files in the repo to be rewritten every time. This is particularly problematic with union filesystems because it means that all unchanged files are rewritten to the top layer.

**Comment by duxsco** [comment]
@mgorny Git doesn't seem to act as outlined by you :)

1. Delete the content of `/var/db/repos/gentoo`
2. Clone an old fork of the "sync" repository:
```
➤ git clone --single-branch --branch stable https://github.com/duxsco/gentoo.git .
Cloning into '.'...
remote: Enumerating objects: 10535788, done.
remote: Total 10535788 (delta 0), reused 0 (delta 0), pack-reused 10535788
Receiving objects: 100% (10535788/10535788), 6.32 GiB | 6.62 MiB/s, done.
Resolving deltas: 100% (8850769/8850769), done.
Updating files: 100% (122256/122256), done.
```
3. Now, the local repo should be in a similar state as after `time git fetch origin` in [my comment](https://bugs.gentoo.org/824782#c17). Switch to upstream mirror:
```
➤ git remote set-url origin https://github.com/gentoo-mirror/gentoo.git
```
4. I have `/var/db/repos/gentoo` content on [a separate BTRFS subvolume](https://github.com/duxsco/gentoo-installation#fstab-configuration). Thus, I made a snapshot:
```
➤ btrfs subvolume snapshot -r @ebuilds @ebuilds_base && sync
Create a readonly snapshot of '@ebuilds' in './@ebuilds_base'
```
5. Do a shallow fetch:
```
➤ git fetch origin --depth 1
remote: Enumerating objects: 1373, done.
remote: Counting objects: 100% (1373/1373), done.
remote: Compressing objects: 100% (436/436), done.
remote: Total 765 (delta 647), reused 407 (delta 327), pack-reused 0
Receiving objects: 100% (765/765), 191.04 KiB | 435.00 KiB/s, done.
Resolving deltas: 100% (647/647), completed with 491 local objects.
From https://github.com/gentoo-mirror/gentoo
 + acfc63d8afdc...0c83b07dea15 stable     -> origin/stable  (forced update)
➤ git rev-parse stable
acfc63d8afdc74ff88f9b0f200a6fe7a09d89b86
➤ git rev-parse origin/stable
0c83b07dea15f4d2c2ca64b96537feab93325015
```
6. Do a hard reset:
```
➤ git reset --hard origin/stable
HEAD is now at 0c83b07dea15 2022-04-01 14:04:46 UTC
```
7. Create another BTRFS snapshot:
```
➤ btrfs subvolume snapshot -r @ebuilds @ebuilds_hard_reset && sync
Create a readonly snapshot of '@ebuilds' in './@ebuilds_hard_reset'
```
8. And, compare content of both snapshots:
[compare.txt](https://github.com/gentoo/portage/files/8398599/compare.txt)

**Comment by duxsco** [comment]
These should be the files that didn't change content-wise, but whose inode changed:
```
➤ git diff --name-only acfc63d8afdc74ff88f9b0f200a6fe7a09d89b86...0c83b07dea15f4d2c2ca64b96537feab93325015 | sort | diff - /tmp/compare.txt | grep -Po "^< \K.*"
dev-cpp/folly/folly-2022.03.07.00.ebuild
dev-java/avalon-framework/files/build.xml
dev-java/jackrabbit-webdav/jackrabbit-webdav-2.21.7.ebuild
dev-java/mchange-commons/mchange-commons-0.2.10-r1.ebuild
dev-lisp/gcl/files/gcl-2.6.12-gcc5.patch
dev-lisp/gcl/gcl-2.6.12.ebuild
dev-python/diskcache/diskcache-5.4.0.ebuild
dev-python/ipykernel/ipykernel-6.6.1.ebuild
dev-python/pdm-pep517/pdm-pep517-0.10.0.ebuild
dev-python/pdm-pep517/pdm-pep517-0.10.1-r1.ebuild
dev-python/pdm-pep517/pdm-pep517-0.10.1.ebuild
dev-python/pdm-pep517/pdm-pep517-0.10.2.ebuild
dev-python/pdm-pep517/pdm-pep517-0.11.0.ebuild
dev-python/pdm-pep517/pdm-pep517-0.11.2.ebuild
dev-python/python-dbusmock/python-dbusmock-0.25.0.ebuild
dev-python/sphinx_ansible_theme/sphinx_ansible_theme-0.9.0.ebuild
dev-util/watchman/watchman-2022.03.07.00.ebuild
media-radio/qrq/qrq-0.3.3.ebuild
media-radio/wsjtx/wsjtx-2.5.0.ebuild
media-radio/wsjtx/wsjtx-2.5.1.ebuild
media-radio/wsjtx/wsjtx-2.5.2.ebuild
media-radio/wsjtx/wsjtx-2.5.3.ebuild
metadata/md5-cache/dev-cpp/folly-2022.03.07.00
metadata/md5-cache/dev-java/jackrabbit-webdav-2.21.7
metadata/md5-cache/dev-java/mchange-commons-0.2.10-r1
metadata/md5-cache/dev-lisp/gcl-2.6.12
metadata/md5-cache/dev-python/diskcache-5.4.0
metadata/md5-cache/dev-python/ipykernel-6.6.1
metadata/md5-cache/dev-python/ipykernel-6.9.1
metadata/md5-cache/dev-python/pdm-pep517-0.10.0
metadata/md5-cache/dev-python/pdm-pep517-0.10.1
metadata/md5-cache/dev-python/pdm-pep517-0.10.1-r1
metadata/md5-cache/dev-python/pdm-pep517-0.10.2
metadata/md5-cache/dev-python/pdm-pep517-0.11.0
metadata/md5-cache/dev-python/pdm-pep517-0.11.2
metadata/md5-cache/dev-python/python-dbusmock-0.25.0
metadata/md5-cache/dev-python/sphinx_ansible_theme-0.9.0
metadata/md5-cache/dev-util/watchman-2022.03.07.00
metadata/md5-cache/media-radio/qrq-0.3.3
metadata/md5-cache/media-radio/wsjtx-2.5.0
metadata/md5-cache/media-radio/wsjtx-2.5.1
metadata/md5-cache/media-radio/wsjtx-2.5.2
metadata/md5-cache/media-radio/wsjtx-2.5.3
metadata/md5-cache/sci-electronics/voacapl-0.7.6
metadata/md5-cache/sci-libs/cartopy-0.19.0
metadata/md5-cache/sci-libs/cartopy-0.20.1
sci-electronics/voacapl/voacapl-0.7.6.ebuild
sci-libs/cartopy/cartopy-0.19.0.ebuild
sci-libs/cartopy/cartopy-0.20.1.ebuild
```

**Comment by mgorny** [comment]
Try overlayfs with squashfs image below.

**Comment by duxsco** [comment]
I did a test with Docker:

```
➤ docker info | sed -n '/^ Storage/,/^ [^[:space:]]/p' | sed '$d'
 Storage Driver: overlay2
  Backing Filesystem: btrfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
```

Execute `docker build -t test -f Dockerfile .` on following Dockerfile:

```
FROM gentoo/stage3

WORKDIR /var/db/repos/gentoo

RUN emerge --quiet --sync && \
    emerge --quiet dev-vcs/git && \
    find . -maxdepth 1 -mindepth 1 -exec rm -rf {} +

RUN git clone --single-branch --branch stable https://github.com/duxsco/gentoo.git . && \
    git remote set-url origin https://github.com/gentoo-mirror/gentoo.git

RUN git fetch origin --depth 1

RUN git reset --hard origin/stable
```

Layer sizes:

```
➤ docker history test
IMAGE          CREATED          CREATED BY                                      SIZE      COMMENT
678e144b797c   2 minutes ago    /bin/sh -c git reset --hard origin/stable       217MB
d212e377d87a   3 minutes ago    /bin/sh -c git fetch origin --depth 1           10.3MB
15cf49483d9c   3 minutes ago    /bin/sh -c git clone --single-branch --branc…   7.29GB
163344d8faae   25 minutes ago   /bin/sh -c emerge --quiet --sync &&     emer…   43MB
1912874699f8   29 minutes ago   /bin/sh -c #(nop) WORKDIR /var/db/repos/gent…   0B
d096b09a72f9   15 hours ago     CMD ["/bin/bash"]                               0B        buildkit.dockerfile.v0
<missing>      15 hours ago     COPY /gentoo/ / # buildkit                      993MB     buildkit.dockerfile.v0
<missing>      15 hours ago     WORKDIR /                                       0B        buildkit.dockerfile.v0
```

So, 217 MB was changed by the hard reset. I think we can live with that. To be honest, AFAIK we cannot go without a hard reset.

**Comment by mgorny** [comment]
I don't think you understand the problem. Rewriting all files on top of squashfs on every sync defeats the purpose of overlay.

**Comment by thesamesam** [comment]
Compromise may be (although I don't love this) reading current depth from disk and reset --hard only if it's changed in settings.

**Comment by duxsco** [comment]
Currently, a shallow clone is done initially (empty `/var/db/repos/gentoo`). As a Gentoo user, I except the local repo to stay shallow. IMHO, it just doesn't make sense to do a shallow clone followed by a non-shallowed fetch prone to a HTTP 504 thereafter.

Users of a squashfs setup should be made aware of the issue and the traditional way of using `rsync` should be recommended to them. I think all other Gentoo users would go with the proposed approach of staying in shallow "mode".

**Comment by mgorny** [comment]
It's really unfortunate that you aren't even trying to find a good solution. You've just made a single decision and now you're focusing on rejecting everything and everyone else just to see it pushed through. This is not how things improve.

**Comment by duxsco** [comment]
I don't understand what you mean. I tried to reproduce the issue of using squashfs with this proposal first with BTRFS and second with Docker plus OverlayFS driver. As I already stated, I cannot think of any other approach to avoid HTTP 504 and not having the whole Git history locally which surely is something that squashfs users wouldn't like to have, too. Suggestions are more than welcome.

**Comment by duxsco** [comment]
@thesamesam Edits by maintainers are allowed on my fork. Can you commit your proposal there, please? The `git reset --hard` commit has been removed and a squash was done.

**Comment by duxsco** [comment]
@thesamesam Or, I could implemented your suggestion. Can you explain what you mean by "settings"? Do you mean portage configuration setting of `sync-depth`?

**Comment by duxsco** [comment]
If you mean by setting the depth of the local repo I have difficulties understanding the suggestion. AFAIK, every fetch with `--depth 1` doesn't allow for anything else other than a hard reset. Otherwise, the screenshot example would have worked in step 3.

**Comment by thesamesam** [comment]
There isn't a need to do it in the scenario you just described?

**Comment by duxsco** [comment]
Can you tell me what you want to execute to bring `stable` branch up-to-date with `origin/stable` if there is no mismatch in depth? I am currently assuming a `git reset --merge` after a shallow fetch.

**Comment by duxsco** [comment]
My bad, I have to correct my assumption of `git reset --merge` not being a viable option. I just didn't see following line:

https://github.com/gentoo/portage/blob/94dad3d64599f7e2c0c28e90ec4bee883746e385/lib/portage/sync/modules/git/git.py#L228

`git reset --merge refs/remotes/origin/stable` works. Shame on me...

But, I cannot explain why same commands don't work in Docker. The Dockerfile:

```
FROM gentoo/stage3

WORKDIR /var/db/repos/gentoo

RUN emerge --quiet --sync && \
    emerge --quiet dev-vcs/git && \
    find . -maxdepth 1 -mindepth 1 -exec rm -rf {} +

RUN git clone --depth 1 https://github.com/duxsco/gentoo.git . && \
    git remote set-url origin https://github.com/gentoo-mirror/gentoo.git

RUN git fetch origin --depth 1

RUN git reset --merge refs/remotes/origin/stable
```

It results in following error which was something that lead me astray:

```
➤ docker build -t test2 -f Dockerfile2 .
Sending build context to Docker daemon  3.072kB
Step 1/6 : FROM gentoo/stage3
 ---> d096b09a72f9
Step 2/6 : WORKDIR /var/db/repos/gentoo
 ---> Running in 837f8f5eff6b
Removing intermediate container 837f8f5eff6b
 ---> ff133388a1e1
Step 3/6 : RUN emerge --quiet --sync &&     emerge --quiet dev-vcs/git &&     find . -maxdepth 1 -mindepth 1 -exec rm -rf {} +
 ---> Running in 664f7c807260
!!! It seems /run is not mounted. Process management may malfunction.

 * IMPORTANT: 12 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.

!!! It seems /run is not mounted. Process management may malfunction.
>>> Verifying ebuild manifests

 * IMPORTANT: 12 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.

>>> Emerging (1 of 14) virtual/perl-Digest-MD5-2.580.0::gentoo
>>> Installing (1 of 14) virtual/perl-Digest-MD5-2.580.0::gentoo
>>> Emerging (2 of 14) dev-perl/TimeDate-2.330.0-r1::gentoo
>>> Installing (2 of 14) dev-perl/TimeDate-2.330.0-r1::gentoo
>>> Emerging (3 of 14) virtual/perl-IO-1.460.0::gentoo
>>> Installing (3 of 14) virtual/perl-IO-1.460.0::gentoo
>>> Emerging (4 of 14) dev-perl/Mozilla-CA-20999999-r1::gentoo
>>> Installing (4 of 14) dev-perl/Mozilla-CA-20999999-r1::gentoo
>>> Emerging (5 of 14) virtual/perl-MIME-Base64-3.160.0::gentoo
>>> Installing (5 of 14) virtual/perl-MIME-Base64-3.160.0::gentoo
>>> Emerging (6 of 14) virtual/perl-Digest-SHA-6.20.0-r2::gentoo
>>> Installing (6 of 14) virtual/perl-Digest-SHA-6.20.0-r2::gentoo
>>> Emerging (7 of 14) dev-perl/Error-0.170.290::gentoo
>>> Installing (7 of 14) dev-perl/Error-0.170.290::gentoo
>>> Emerging (8 of 14) dev-perl/Digest-HMAC-1.40.0::gentoo
>>> Installing (8 of 14) dev-perl/Digest-HMAC-1.40.0::gentoo
>>> Emerging (9 of 14) dev-perl/Net-SSLeay-1.900.0::gentoo
>>> Installing (9 of 14) dev-perl/Net-SSLeay-1.900.0::gentoo
>>> Emerging (10 of 14) dev-perl/Authen-SASL-2.160.0-r2::gentoo
>>> Installing (10 of 14) dev-perl/Authen-SASL-2.160.0-r2::gentoo
>>> Emerging (11 of 14) dev-perl/IO-Socket-SSL-2.72.0::gentoo
>>> Installing (11 of 14) dev-perl/IO-Socket-SSL-2.72.0::gentoo
>>> Emerging (12 of 14) virtual/perl-libnet-3.130.0::gentoo
>>> Installing (12 of 14) virtual/perl-libnet-3.130.0::gentoo
>>> Emerging (13 of 14) dev-perl/MailTools-2.210.0::gentoo
>>> Installing (13 of 14) dev-perl/MailTools-2.210.0::gentoo
>>> Emerging (14 of 14) dev-vcs/git-2.35.1::gentoo
>>> Installing (14 of 14) dev-vcs/git-2.35.1::gentoo
>>> Recording dev-vcs/git in "world" favorites file...
 * Messages for package dev-vcs/git-2.35.1:
 * Please read /usr/share/bash-completion/completions/git for Git bash command
 * completion.
 * Please read /usr/share/git/git-prompt.sh for Git bash prompt
 * Note that the prompt bash code is now in that separate script
 * These additional scripts need some dependencies:
 *   git-quiltimport  : dev-util/quilt
 *   git-instaweb     : || ( www-servers/lighttpd www-servers/apache www-servers/nginx )



 * IMPORTANT: 12 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.

Removing intermediate container 664f7c807260
 ---> eb262a08af79
Step 4/6 : RUN git clone --depth 1 https://github.com/duxsco/gentoo.git . &&     git remote set-url origin https://github.com/gentoo-mirror/gentoo.git
 ---> Running in 1d7278147b90
Cloning into '.'...
Updating files: 100% (122256/122256), done.
Removing intermediate container 1d7278147b90
 ---> 38ac25f7a548
Step 5/6 : RUN git fetch origin --depth 1
 ---> Running in 615a37a8b9cc
From https://github.com/gentoo-mirror/gentoo
 + acfc63d8a...5b1fc2eb9 stable     -> origin/stable  (forced update)
Removing intermediate container 615a37a8b9cc
 ---> 38aa64aef2bd
Step 6/6 : RUN git reset --merge refs/remotes/origin/stable
 ---> Running in 00b276cbf51a
error: Entry 'app-admin/ansible-lint/Manifest' not uptodate. Cannot merge.
fatal: Could not reset index file to revision 'refs/remotes/origin/stable'.
The command '/bin/sh -c git reset --merge refs/remotes/origin/stable' returned a non-zero code: 128
```

But, same commands executed in a terminal succeed.

**Comment by duxsco** [comment]
This Dockerfile with the only change in the last `RUN`, however, works for Docker:

```
FROM gentoo/stage3

WORKDIR /var/db/repos/gentoo

RUN emerge --quiet --sync && \
    emerge --quiet dev-vcs/git && \
    find . -maxdepth 1 -mindepth 1 -exec rm -rf {} +

RUN git clone --depth 1 https://github.com/duxsco/gentoo.git . && \
    git remote set-url origin https://github.com/gentoo-mirror/gentoo.git

RUN git fetch origin --depth 1

RUN git reset --hard refs/remotes/origin/stable
```

**Comment by duxsco** [comment]
In my view, this PR is complete. The Docker issue is bothering me, though.

**Comment by thesamesam** [comment]
Why close this PR and open a new one? It means we lose all the reviewing context :(

**Comment by duxsco** [comment]
sry, I accidentally deleted the wrong repo, and this PR was consequently closed. I wasn't able to reopen this.

**Comment by duxsco** [comment]
I have to correct my statement of rsync being a viable option for squashfs users:
https://bugs.gentoo.org/660410#c2

Setting `sync-allow-hardlinks = no` as brought forth in the bug report would lead to an independent copy of the ebuild repository for each `emerge --sync` which is s.th. squashfs users wouldn't want.

If you really want to have minimal changes on disk:
1. The initial `emerge --sync` should be done with rsync option `--sparse`.
2. All following `emerge --sync` should be done with rsync options `--inplace` and `--no-whole-file` instead of `--sparse`. See: https://superuser.com/a/674634

But, this would make the use of a quarantine directory impossible which is s.th. all users wouldn't want.

As a compromise, a portage option `sync-allow-inplace` could be introduced with the options in bullet point 2 being enabled and the drawback of having `/var/db/repos/gentoo` in an inconsistent state in the worst case which is s.th. users must be made aware of.

**Comment by duxsco** [comment]
FYI. On my test install, a `git reset --merge` is causing the same problem that I add in a Docker container:

screenshot_2022-04-03-224536-fs8

It works, however, with a hard reset:

screenshot_2022-04-03-224801-fs8

**Comment by duxsco** [comment]
hm, I did another `emerge -sync` with original portage. And, the `git reset --merge` succeeded this time. I don't understand what's causing this:
> error: Entry 'app-group/rspamd/metadata.xml' not uptodate. Cannot merge.
> fatal: Could not reset index file to revision 'refs/remotes/origin/master'.

**Comment by duxsco** [comment]
As I am not getting anywhere with https://github.com/gentoo/portage/pull/801, I decided to write a non-squashfs/overlayfs solution:
https://github.com/duxsco/gentoo-git

I leave the PR as is and take care of other stuff 🙂

**Pull request closed without merging**
