### PR TITLE
actions: drop duplication of --help logic

### PR DESCRIPTION
**Pull request by berinaniesh**
Force push amends the previous commit with a signed-off tag and a detailed description of the commit message.

### CODE REVIEW

**Comment by thesamesam** [comment]
1. Please make the commit summary (first line) more descriptive, like `actions: drop duplication of --help logic`
2. Please describe in the commit message how you determined it's redundant. e.g. "It's safe to remove this because ...." or "We were duplicating logic between X and Y, it's already called at ...".

**Comment by berinaniesh** [comment]
@thesamesam Should I amend the commit and force push again?

**Comment by thesamesam** [comment]
yes please! :)

**Comment by thesamesam** [comment]
Nice find, thanks! This is exactly the sort of thing I was hoping you'd find to start off with, as you get familiar with the codebase.

**Pull request closed without merging**
