### PR TITLE
Adjust write tests for DISTDIR and PORTAGE_TMPDIR to work with automount directories

### PR DESCRIPTION
**Pull request by floppym**
Bug: https://bugs.gentoo.org/485100
Bug: https://bugs.gentoo.org/890812

### CODE REVIEW

**Comment by floppym** [comment]
If anyone wants to test this, you can set up an automount using systemd via an fstab entry like this:
```
tmpfs /path/to/mount tmpfs mode=0770,uid=root,gid=portage,x-systemd.automount
```
Then run `systemctl daemon-reload` and `systemctl start path-to-mount.automount.

**Comment by thesamesam** [comment]
I'll test this out tomorrow, thank you!

**Comment by thesamesam** [comment]
> If anyone wants to test this, you can set up an automount using systemd via an fstab entry like this:
> 
> ```
> tmpfs /path/to/mount tmpfs mode=0770,uid=root,gid=portage,x-systemd.automount 0 0
> ```
> 
> Then run `systemctl daemon-reload` and `systemctl start path-to-mount.automount`.

The patch lgtm, but I couldn't reproduce the bug with:
```
tmpfs /mnt/testing-this-bug tmpfs mode=0770,uid=root,gid=portage,x-systemd.automount 0 0
```

I could see this when I start the automount:
```
systemd-1 on /mnt/testing-this-bug type autofs (rw,relatime,fd=60,pgrp=1,timeout=0,minproto=5,maxproto=5,direct)
```

And after Portage tries to use it with `PORTAGE_TMPDIR=/mnt/testing-this-bug emerge -v1 google-chrome`:
```
tmpfs on /mnt/testing-this-bug type tmpfs (rw,relatime,mode=770,gid=250,x-systemd.automount)
```

**Comment by floppym** [comment]
To reproduce the original issue, I guess you would need to include "/portage" in the mount point. For example:
```
tmpfs /mnt/testing-this-bug/portage tmpfs mode=0770,uid=root,gid=portage,x-systemd.automount 0 0
```
Then, set `PORTAGE_TMPDIR=/mnt/testing-this-bug`

**Comment by thesamesam** [comment]
Ah, thanks! I should've clocked that. Let me try.

**Review by thesamesam — APPROVED** [review]
Reproduced, thanks!

It might be nice to put that in the commit message but it's not a big deal if you object.

**Comment by floppym** [comment]
Can do.

**Pull request merged**
