### PR TITLE
Repoman: PEP8 fixes & build dependency

### PR DESCRIPTION
**Pull request by elacheche**

### CODE REVIEW

**Comment by dol-sen** [comment]
All these commits above have been cherrypicked into the initial repoman stage3 PR
https://github.com/gentoo/portage/pull/202

Ping me if you add any new ones to this so I can add them.

**Comment by mjeveritt** [comment]
Given new interest in linting portage, is this worth revisiting? @zmedico @dol-sen

**Comment by mjeveritt** [comment]
ere @flappyports

**Comment by floppym** [comment]
repoman is gone.

**Pull request closed without merging**
