### PR TITLE
[PREFIX] bin/*: fix hardcoded shebangs

### PR DESCRIPTION
**Pull request by CyberTailor**
Relace with @PREFIX_PORTAGE_PYTHON@ and @PORTAGE_BASH@ (where
appropriate).

### CODE REVIEW

**Comment by floppym** [comment]
It would be nice to have a solution that would allow usage from a git checkout without installation.

**Comment by CyberTailor** [comment]
> It would be nice to have a solution that would allow usage from a git checkout without installation.

Portage from the `master` branch doesn't use autotools. These changes only affect the `prefix` branch.

**Comment by grobian** [comment]
this is not entirely true, we use the python based install from the ebuild, the autoconf-based one from bootstrap-prefix

As to be able to run from a development snapshot, with Prefix tools this is really difficult if you don't want/can't use /usr/bin/env.  In the past this wasn't possible due to using python -b and so on.  Not sure how that is today.

**Comment by floppym** [comment]
> As to be able to run from a development snapshot, with Prefix tools this is really difficult if you don't want/can't use /usr/bin/env. In the past this wasn't possible due to using python -b and so on. Not sure how that is today.

We already switched to using /usr/bin/env on the master branch See 41f4f6d25019c4f944b8d9576d96482f92231fda and 781aefd8be33c3bd699e5a665225013c5f76b531.

**Comment by grobian** [comment]
I basicall did this

**Pull request closed without merging**
