### PR TITLE
Support cross-root package moves

### PR DESCRIPTION
**Pull request by zmedico**
Bug: https://bugs.gentoo.org/946326

### CODE REVIEW

**Comment by floppym** [comment]
I just tried this PR, and I'm still not getting any global updates applied when I run `aarch64-unknown-linux-gnu-emerge -uDNav @world`.
```
% cat /usr/local/bin/aarch64-unknown-linux-gnu-emerge
#!/bin/bash
self=${0##*/}
host=${self%-emerge}
export ROOT=/usr/${host}
export PORTAGE_CONFIGROOT=${ROOT}
export SYSROOT=${ROOT}
exec emerge "$@"
```

**Comment by zmedico** [comment]
> I just tried this PR, and I'm still not getting any global updates applied when I run `aarch64-unknown-linux-gnu-emerge -uDNav @world`.

You may need to delete the previous mtimedb for this root, because it contains timestamps indicating that package moves were already applied.

**Comment by floppym** [comment]
Removing /usr/aarch64-unknown-linux-gnu/var/cache/edb/mtimedb had no effect.

**Comment by zmedico** [comment]
> Removing /usr/aarch64-unknown-linux-gnu/var/cache/edb/mtimedb had no effect.

Sorry, hopefully it works now. The _global_updates function is now enabled for `len(trees) != 1`.

**Comment by floppym** [comment]
Ok, seems to be working now. Thanks!

**Pull request merged**
