### PR TITLE
bintree : Add object invalid_paths

### PR DESCRIPTION
**Pull request by siddhanthrathod**
for new eclean feature to deal with invalid binpkgs

### CODE REVIEW

**Comment by dol-sen** [comment]
looks good.  waiting for more complete eclean patch that handles older portage without puking.

**Comment by floppym** [comment]
Please fix the spelling of "invalid_paths" in the commit summary. It currently says "inavlid_paths".

**Comment by ZeroChaos-** [comment]
bump, this is still needed I think

**Comment by thesamesam** [comment]
I'd like the gentoolkit side to be finalised first so we don't have to change the API later.

**Comment by ZeroChaos-** [comment]
> I'd like the gentoolkit side to be finalised first so we don't have to change the API later.

Is it not? It looked like all the comments were addressed and it was working? https://github.com/gentoo/gentoolkit/pull/28

**Comment by thesamesam** [comment]
dol-sen hasn't re-reviewed it.

**Comment by mattst88** [comment]
> siddhanthrathod requested a review from dol-sen last month

**Comment by siddhanthrathod** [comment]
@dol-sen will add this feature in the upcoming gentoolkit bump. He said it looked good to him on irc chat.

**Pull request closed without merging**
