### PR TITLE
EbuildMetadataPhase: Add deallocate_config future

### PR DESCRIPTION
**Pull request by zmedico**
Seeing intermittent failures for start-method spawn like these:
https://github.com/gentoo/portage/actions/runs/7881445624/job/21505078453
```
2024-02-13T03:58:08.0646108Z =================================== FAILURES ===================================
2024-02-13T03:58:08.0646351Z _________________ lib/portage/tests/util/futures/test_retry.py _________________
2024-02-13T03:58:08.0646825Z [gw3] linux -- Python 3.12.2 /opt/hostedtoolcache/Python/3.12.2/x64/bin/python
2024-02-13T03:58:08.0647599Z worker 'gw3' crashed while running 'lib/portage/tests/util/futures/test_retry.py::RetryForkExecutorTestCase::testOverallTimeoutWithTimeoutError'
2024-02-13T03:58:08.0647839Z _________________ lib/portage/tests/ebuild/test_ipc_daemon.py __________________
2024-02-13T03:58:08.0648146Z [gw0] linux -- Python 3.12.2 /opt/hostedtoolcache/Python/3.12.2/x64/bin/python
2024-02-13T03:58:08.0648683Z worker 'gw0' crashed while running 'lib/portage/tests/ebuild/test_ipc_daemon.py::IpcDaemonTestCase::testIpcDaemon'
```
https://github.com/gentoo/portage/actions/runs/7881695867/job/21505735793
```
2024-02-13T04:33:58.8748178Z =================================== FAILURES ===================================
2024-02-13T04:33:58.8748721Z ______________ lib/portage/tests/process/test_spawn_returnproc.py ______________
2024-02-13T04:33:58.8749432Z [gw1] linux -- Python 3.12.1 /opt/hostedtoolcache/Python/3.12.1/x64/bin/python
2024-02-13T04:33:58.8750541Z worker 'gw1' crashed while running 'lib/portage/tests/process/test_spawn_returnproc.py::SpawnReturnProcTestCase::testSpawnReturnProcWait'
```
https://github.com/gentoo/portage/actions/runs/7881816146/job/21506044613
```
2024-02-13T04:51:38.8635997Z =================================== FAILURES ===================================
2024-02-13T04:51:38.8636255Z ______________ lib/portage/tests/locks/test_asynchronous_lock.py _______________
2024-02-13T04:51:38.8636576Z [gw1] linux -- Python 3.12.1 /opt/hostedtoolcache/Python/3.12.1/x64/bin/python
2024-02-13T04:51:38.8637323Z worker 'gw1' crashed while running 'lib/portage/tests/locks/test_asynchronous_lock.py::AsynchronousLockTestCase::testAsynchronousLockWaitKill'
```
Bug: https://bugs.gentoo.org/923841
Bug: https://bugs.gentoo.org/924319
Fixes: c95fc64abf96 ("EbuildPhase: async_check_locale")

### CODE REVIEW

**Review by thesamesam — COMMENTED** [review]
It sounds okay and worth trying but I don't feel that confident in giving a useful review on this one.

**Comment by thesamesam** [comment]
Do you think you could try for a testcase (maybe just fetch gentoo.git w/ metadata as a snapshot from commit at https://gitweb.gentoo.org/repo/sync/gentoo.git/, then sed a bunch, then egencache --jobs=$(nproc) or so)?

**Comment by zmedico** [comment]
> Do you think you could try for a testcase (maybe just fetch gentoo.git w/ metadata as a snapshot from commit at https://gitweb.gentoo.org/repo/sync/gentoo.git/, then sed a bunch, then egencache --jobs=$(nproc) or so)?

Yeah I'll come up with some kind of test. Not sure if gentoo.git is really a good data source for this because it's so big. Hopefully just a ResolverPlayground with some ebuilds generated in a loop will be good enough.

**Comment by zmedico** [comment]
> > Do you think you could try for a testcase (maybe just fetch gentoo.git w/ metadata as a snapshot from commit at https://gitweb.gentoo.org/repo/sync/gentoo.git/, then sed a bunch, then egencache --jobs=$(nproc) or so)?
> 
> Yeah I'll come up with some kind of test. Not sure if gentoo.git is really a good data source for this because it's so big. Hopefully just a ResolverPlayground with some ebuilds generated in a loop will be good enough.
> 
> It might be enough to trigger the bug if we just change ResolverPlayground._create_ebuild_manifests to call `egencache --update --update-manifests --jobs=$(nproc)`.

I made the ResolverPlayground _create_ebuild_manifests method call egencache --jobs, which reliably triggers the KeyError from bug 924319 for multiple tests:
```
lib/portage/tests/bin/test_doins.py::DoIns::testDoInsFallback Exception in callback EbuildMetadataPhase._async_start_done(<Task finishe...Error('EAPI')>)
handle: <Handle EbuildMetadataPhase._async_start_done(<Task finishe...Error('EAPI')>)>
Traceback (most recent call last):
  File "/usr/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "lib/_emerge/EbuildMetadataPhase.py", line 154, in _async_start_done
    future.cancelled() or future.result()
                          ^^^^^^^^^^^^^^^
  File "lib/_emerge/EbuildMetadataPhase.py", line 130, in _async_start
    retval = portage.doebuild(
             ^^^^^^^^^^^^^^^^^
  File "lib/portage/package/ebuild/doebuild.py", line 1030, in doebuild
    doebuild_environment(
  File "lib/portage/package/ebuild/doebuild.py", line 519, in doebuild_environment
    eapi = mysettings.configdict["pkg"]["EAPI"]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "lib/portage/util/__init__.py", line 1684, in __getitem__
    return UserDict.__getitem__(self, item_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/portage/cache/mappings.py", line 175, in __getitem__
    return self.data[key]
           ~~~~~~~~~^^^^^
KeyError: 'EAPI'
```

**Comment by zmedico** [comment]
Will close this and attempt to gradually merge the commits related to https://bugs.gentoo.org/923841.

**Comment by zmedico** [comment]
Due to intermittent test failures for the spawn start-method, I'll close this and attempt to gradually merge the commits related to https://bugs.gentoo.org/923841.

**Pull request closed without merging**
